### ISSUE TITLE
KeyError: 'features.0.scale'

### ISSUE THREAD

**Issue by sakurachiyuki** [kamwoh/DeepIPR#1]
Thank you for the code.

When i run ' python passport_attack_1.py --loadpath  ./ logs/alexnet_cifar10_v1/2/models/best.pth --passport-config ./passport_configs/alexnet_passport.json'.
I got ‘KeyError: 'features.0.scale’ .
I'm not sure what's wrong with it.Thanks again.

**Comment by kamwoh** [comment]
Hi, this was a bug I didn't take care of when I was cleaning up the code for the first release, I have noticed this a long time ago. I have fixed it with the latest release.
